"""empty message

Revision ID: 0519b333d426
Revises: e0b14078a0c2
Create Date: 2022-08-13 19:38:46.105433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0519b333d426'
down_revision = 'e0b14078a0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('gender', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'gender')
    # ### end Alembic commands ###
